/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.wh.ws;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int alphl=0x7f040001;
        public static final int apptn=0x7f040004;
        public static final int appts=0x7f040005;
        public static final int black=0x7f040011;
        public static final int btn_normal=0x7f040006;
        public static final int btn_selected=0x7f040007;
        public static final int bulue=0x7f040003;
        public static final int click_item_selected=0x7f04000e;
        public static final int feel_item_color=0x7f040008;
        public static final int la_1=0x7f040012;
        public static final int la_2=0x7f040013;
        public static final int la_3=0x7f040014;
        public static final int la_4=0x7f040015;
        public static final int panal_color=0x7f04000c;
        public static final int ruelepre_normal=0x7f040016;
        public static final int ruelepre_selected=0x7f040017;
        public static final int text_line_bg=0x7f04000d;
        public static final int title_bg=0x7f040002;
        public static final int video_contral_normal=0x7f040010;
        public static final int video_contral_selected=0x7f04000f;
        public static final int vv_none=0x7f04000b;
        public static final int vv_selected=0x7f040009;
        public static final int vv_unselected=0x7f04000a;
        public static final int whiles=0x7f040000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int ani_top=0x7f020000;
        public static final int arrow=0x7f020001;
        public static final int arrow_normal=0x7f020002;
        public static final int arrow_rule_normal=0x7f020003;
        public static final int arrow_rule_selected=0x7f020004;
        public static final int arrow_selected=0x7f020005;
        public static final int btn_click=0x7f020006;
        public static final int btn_click_qx=0x7f020007;
        public static final int btn_delete=0x7f020008;
        public static final int btn_eidt=0x7f020009;
        public static final int btn_play=0x7f02000a;
        public static final int buttom_pouse=0x7f02000b;
        public static final int buttom_star=0x7f02000c;
        public static final int button_camera=0x7f02000d;
        public static final int button_contral=0x7f02000e;
        public static final int button_img_camera_normal=0x7f02000f;
        public static final int button_img_camera_selected=0x7f020010;
        public static final int button_img_contral_normal=0x7f020011;
        public static final int button_img_contral_selected=0x7f020012;
        public static final int button_img_smart_normal=0x7f020013;
        public static final int button_img_smart_selected=0x7f020014;
        public static final int button_img_video_normal=0x7f020015;
        public static final int button_img_video_selected=0x7f020016;
        public static final int button_img_zn_normal=0x7f020017;
        public static final int button_img_zn_selected=0x7f020018;
        public static final int button_play=0x7f020019;
        public static final int button_qx=0x7f02001a;
        public static final int button_smart=0x7f02001b;
        public static final int button_video=0x7f02001c;
        public static final int button_zn=0x7f02001d;
        public static final int camera=0x7f02001e;
        public static final int circle_end=0x7f02001f;
        public static final int circle_star=0x7f020020;
        public static final int click_item=0x7f020021;
        public static final int contral_bg=0x7f020022;
        public static final int contral_bg_fra=0x7f020023;
        public static final int contral_bg_selected=0x7f020024;
        public static final int contral_circle=0x7f020025;
        public static final int contral_focus=0x7f020026;
        public static final int contral_img_circle_normal=0x7f020027;
        public static final int contral_img_cricle_selected=0x7f020028;
        public static final int contral_img_foucs_normal=0x7f020029;
        public static final int contral_img_foucs_selected=0x7f02002a;
        public static final int contral_img_jfoucs_normal=0x7f02002b;
        public static final int contral_img_jfoucs_selected=0x7f02002c;
        public static final int contral_img_point_normal=0x7f02002d;
        public static final int contral_img_point_selected=0x7f02002e;
        public static final int contral_img_refresh_normal=0x7f02002f;
        public static final int contral_img_refresh_selected=0x7f020030;
        public static final int contral_jfocus=0x7f020031;
        public static final int contral_point=0x7f020032;
        public static final int contral_refresh=0x7f020033;
        public static final int eidit_shape=0x7f020034;
        public static final int eidit_shape1=0x7f020035;
        public static final int feel_ib=0x7f020036;
        public static final int feel_img=0x7f020037;
        public static final int feel_img_normal=0x7f020038;
        public static final int feel_img_selected=0x7f020039;
        public static final int feel_item_click=0x7f02003a;
        public static final int fgt_add=0x7f02003b;
        public static final int focus_end=0x7f02003c;
        public static final int foucs_start=0x7f02003d;
        public static final int ic_launcher=0x7f02003e;
        public static final int img=0x7f02003f;
        public static final int img_1=0x7f020040;
        public static final int img_2=0x7f020041;
        public static final int img_3=0x7f020042;
        public static final int img_4=0x7f020043;
        public static final int img_arrow=0x7f020044;
        public static final int img_buttom=0x7f020045;
        public static final int img_edit=0x7f020046;
        public static final int img_feel=0x7f020047;
        public static final int img_ivm=0x7f020048;
        public static final int img_left=0x7f020049;
        public static final int img_right=0x7f02004a;
        public static final int img_set=0x7f02004b;
        public static final int img_titile_back=0x7f02004c;
        public static final int img_titile_right=0x7f02004d;
        public static final int img_title_left=0x7f02004e;
        public static final int img_top=0x7f02004f;
        public static final int img_type_cut=0x7f020050;
        public static final int img_type_l=0x7f020051;
        public static final int img_type_r=0x7f020052;
        public static final int img_type_warn=0x7f020053;
        public static final int img_video=0x7f020054;
        public static final int img_warm=0x7f020055;
        public static final int img_yl=0x7f020056;
        public static final int img_zn=0x7f020057;
        public static final int item_default=0x7f020058;
        public static final int ivdeo_play=0x7f020059;
        public static final int ivideo_big=0x7f02005a;
        public static final int ivideo_camera=0x7f02005b;
        public static final int ivideo_voice=0x7f02005c;
        public static final int jfoucs_end=0x7f02005d;
        public static final int jfoucs_star=0x7f02005e;
        public static final int left_right=0x7f02005f;
        public static final int list_item_click=0x7f020060;
        public static final int ruelepra_edit=0x7f020061;
        public static final int rule_arrow_child=0x7f020062;
        public static final int rulepre__btn=0x7f020063;
        public static final int rulepre_delete=0x7f020064;
        public static final int rulepre_play=0x7f020065;
        public static final int rulepre_play_nomal=0x7f020066;
        public static final int set_img_about=0x7f020067;
        public static final int set_img_dvd=0x7f020068;
        public static final int set_img_heat=0x7f020069;
        public static final int set_img_help=0x7f02006a;
        public static final int set_img_pwd=0x7f02006b;
        public static final int vb_bg=0x7f02006c;
        public static final int video_big=0x7f02006d;
        public static final int video_camra=0x7f02006e;
        public static final int video_cut=0x7f02006f;
        public static final int video_hava_voice=0x7f020070;
        public static final int video_no_voice=0x7f020071;
        public static final int video_play=0x7f020072;
        public static final int video_pouse=0x7f020073;
        public static final int video_small=0x7f020074;
        public static final int wheel_bg=0x7f020075;
        public static final int wheel_val=0x7f020076;
    }
    public static final class id {
        public static final int ac_tv=0x7f090013;
        public static final int act_center_video=0x7f090005;
        public static final int act_feel_btn=0x7f090004;
        public static final int act_feel_item=0x7f090001;
        public static final int act_item_epd=0x7f090008;
        public static final int act_item_ll=0x7f090009;
        public static final int act_set_item=0x7f090011;
        public static final int act_video_rl_time_end=0x7f090014;
        public static final int act_video_rl_time_star=0x7f090012;
        public static final int act_warn_ll=0x7f090016;
        public static final int act_warn_lv=0x7f090015;
        public static final int action_settings=0x7f09004b;
        public static final int button_ll_btns=0x7f090019;
        public static final int chooise_gn=0x7f09001a;
        public static final int dialog_ib_feel=0x7f09001f;
        public static final int dialog_ib_ivm=0x7f09001e;
        public static final int dialog_ib_other=0x7f090022;
        public static final int dialog_ib_set=0x7f090021;
        public static final int dialog_ib_vmanager=0x7f09001c;
        public static final int dialog_ib_warms=0x7f09001d;
        public static final int dialog_ib_yl=0x7f09001b;
        public static final int dialog_ib_zn=0x7f090020;
        public static final int fgt_buttom=0x7f09002d;
        public static final int fgt_contrals=0x7f09002a;
        public static final int fgt_drawx=0x7f09002f;
        public static final int fgt_ib_add=0x7f090030;
        public static final int fgt_left=0x7f09002c;
        public static final int fgt_right=0x7f09002e;
        public static final int fgt_top=0x7f09002b;
        public static final int fgt_tv=0x7f090029;
        public static final int fgt_video=0x7f090028;
        public static final int gride_iv=0x7f090036;
        public static final int info_item_iv=0x7f090046;
        public static final int info_item_iv_edit=0x7f090047;
        public static final int info_item_tv_address=0x7f090049;
        public static final int info_item_tv_date=0x7f09004a;
        public static final int info_item_tv_name=0x7f090048;
        public static final int iomact_mylv=0x7f090031;
        public static final int iov_item_gv=0x7f090038;
        public static final int iov_item_tv=0x7f090037;
        public static final int item_contral_one=0x7f090035;
        public static final int item_my_iv=0x7f090002;
        public static final int item_my_tv=0x7f090003;
        public static final int item_parent_my_iv=0x7f09003a;
        public static final int item_parent_my_tv=0x7f09003b;
        public static final int item_qx_qxs=0x7f090039;
        public static final int iv=0x7f090033;
        public static final int main_buttom_ll_contral=0x7f090018;
        public static final int main_center=0x7f090017;
        public static final int pb=0x7f090034;
        public static final int rule_child_imgbtn1=0x7f09003f;
        public static final int rule_child_imgbtn2=0x7f090040;
        public static final int rule_child_imgbtn3=0x7f090041;
        public static final int rule_expandablelistview=0x7f09000a;
        public static final int rule_item_step1=0x7f09003c;
        public static final int rule_item_step2=0x7f09003d;
        public static final int rule_item_step3=0x7f09003e;
        public static final int rule_parent_imgbtn=0x7f090043;
        public static final int rule_parent_tv=0x7f090042;
        public static final int rulepre_fgt=0x7f09000c;
        public static final int rulepre_ibtn_delete=0x7f090010;
        public static final int rulepre_ibtn_eidt=0x7f09000e;
        public static final int rulepre_ibtn_play=0x7f09000f;
        public static final int rulepre_ll=0x7f09000b;
        public static final int rulepre_rule=0x7f09000d;
        public static final int searchView1=0x7f090000;
        public static final int title_ib_left=0x7f090044;
        public static final int title_ib_rights=0x7f090007;
        public static final int title_tv_center=0x7f090006;
        public static final int tv=0x7f090032;
        public static final int video_contral_item=0x7f090045;
        public static final int wheel_1=0x7f090023;
        public static final int wheel_2=0x7f090024;
        public static final int wheel_3=0x7f090025;
        public static final int wheel_4=0x7f090026;
        public static final int wheel_5=0x7f090027;
    }
    public static final class layout {
        public static final int act_dvd=0x7f030000;
        public static final int act_feel=0x7f030001;
        public static final int act_feel_video=0x7f030002;
        public static final int act_image=0x7f030003;
        public static final int act_item=0x7f030004;
        public static final int act_luy_video=0x7f030005;
        public static final int act_marketset=0x7f030006;
        public static final int act_ori=0x7f030007;
        public static final int act_rulepre=0x7f030008;
        public static final int act_set=0x7f030009;
        public static final int act_videomanager=0x7f03000a;
        public static final int act_warninfo=0x7f03000b;
        public static final int activity_main=0x7f03000c;
        public static final int dialog_choose=0x7f03000d;
        public static final int dialog_wheelview=0x7f03000e;
        public static final int fgt_v=0x7f03000f;
        public static final int img_orvideo_manager=0x7f030010;
        public static final int item_contral=0x7f030011;
        public static final int item_gride=0x7f030012;
        public static final int item_iov=0x7f030013;
        public static final int item_qx=0x7f030014;
        public static final int my_childitem=0x7f030015;
        public static final int my_parent=0x7f030016;
        public static final int rule_item=0x7f030017;
        public static final int rule_my_child=0x7f030018;
        public static final int rule_my_parent=0x7f030019;
        public static final int title=0x7f03001a;
        public static final int video_contral=0x7f03001b;
        public static final int waring_item=0x7f03001c;
    }
    public static final class menu {
        public static final int main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int hello_world=0x7f070002;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060001;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060002;
        public static final int custom=0x7f060000;
    }
}
